name: Build and deploy ASP.Net Core app to Azure Web App - webbanhang

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/Web/Web.csproj

    - name: Build
      run: dotnet build src/Web/Web.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish src/Web/Web.csproj --configuration Release --output ./publish --no-build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webbanhang'  # <-- Tên App Service của bạn
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'
